//constants for creating and order in our DB
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

//constants for order screen
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

//orders list for user
export const ORDER_MINE_LIST_REQUEST = "ORDER_MINE_LIST_REQUEST"
export const ORDER_MINE_LIST_SUCCESS = "ORDER_MINE_LIST_SUCCESS"
export const ORDER_MINE_LIST_FAIL = "ORDER_MINE_LIST_FAIL"

//orders list request from admin
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL"

//delete order request

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST"
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS"
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL"
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET"
